In [1]:
# Go to https://pytorch.org/get-started/locally and install for your local configuration
# !pip install pyarrow transformers datasets [evaluate]
# <conda/mamba> install pyarrow transformers datasets [evaluate]

In [7]:
import torch
from transformers import AutoTokenizer, AutoModel, # BERTModel

/home/tshoe/env/envs/nlp/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [10]:
"This is a [MASK] of text".split()

['This', 'is', 'a', '[MASK]', 'of', 'text']

In [8]:
checkpoint = "google-bert/bert-base-uncased"
tokenizer = AutoTokenizer.from_pretrained(checkpoint)
bert = AutoModel.from_pretrained(checkpoint)

In [31]:
phrase = "large language models use subword tokenization, which produces oddtokens"

In [32]:
tokens = tokenizer(phrase)
tokenizer.decode(tokens["input_ids"])

'[CLS] large language models use subword tokenization, which produces oddtokens [SEP]'

In [150]:
tokens = tokenizer("239487514280981305.201389423")
for tokid in tokens["input_ids"]:
    print(tokenizer.decode(tokid))

[CLS]
239
##48
##75
##14
##28
##0
##9
##8
##13
##0
##5
.
2013
##8
##9
##42
##3
[SEP]


In [22]:
len(phrase.split())

6

In [23]:
len(tokens["input_ids"])

10

In [24]:
for tokid in tokens["input_ids"]:
    token = tokenizer.decode(tokid)
    print(token)

[CLS]
large
language
models
use
sub
##word
token
##ization
[SEP]


In [25]:
phrase

'large language models use subword tokenization'

In [ ]:
" SolidGoldMagikarp"

In [35]:
sentence = "Then I tried to find some way of embracing my mother's ghost."
inputs = tokenizer(
    sentence, return_tensors = "pt", return_attention_mask = True 
)

In [36]:
inputs

{'input_ids': tensor([[  101,  2059,  1045,  2699,  2000,  2424,  2070,  2126,  1997, 23581,
          2026,  2388,  1005,  1055,  5745,  1012,   102]]), 'token_type_ids': tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])}

In [37]:
inputs["input_ids"]

tensor([[  101,  2059,  1045,  2699,  2000,  2424,  2070,  2126,  1997, 23581,
          2026,  2388,  1005,  1055,  5745,  1012,   102]])

In [38]:
tokenizer.decode([1005, 1012])

"'."

In [39]:
ws = tokenizer(" \t\n")
ws["input_ids"]

[101, 102]

In [40]:
tokenizer.decode(ws["input_ids"])

'[CLS] [SEP]'

In [41]:
inputs["token_type_ids"]

tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [42]:
question = "What did I do then?"
with_token_types = tokenizer(question, sentence)
with_token_types["token_type_ids"]

[0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

In [43]:
inputs["attention_mask"]

tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [44]:
two_sequence_inputs = tokenizer(
    [question, sentence],
    return_tensors = "pt",
    return_attention_mask = True,
    padding = "longest"
)
two_sequence_inputs["input_ids"]

tensor([[  101,  2054,  2106,  1045,  2079,  2059,  1029,   102,     0,     0,
             0,     0,     0,     0,     0,     0,     0],
        [  101,  2059,  1045,  2699,  2000,  2424,  2070,  2126,  1997, 23581,
          2026,  2388,  1005,  1055,  5745,  1012,   102]])

In [45]:
two_sequence_inputs["attention_mask"]

tensor([[1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [46]:
two_sequence_inputs = tokenizer(
    [question, sentence],
    return_tensors = "pt",
    return_attention_mask = True,
    padding = "max_length"
)
two_sequence_inputs["input_ids"][0]

tensor([ 101, 2054, 2106, 1045, 2079, 2059, 1029,  102,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,   

In [47]:
print("Context window size:", tokenizer.model_max_length)

Context window size: 512


In [48]:
too_long = "a " * 10_000
too_long_inputs = tokenizer(
    too_long, return_tensors = "pt", return_attention_mask = True
)

Token indices sequence length is longer than the specified maximum sequence length for this model (10002 > 512). Running this sequence through the model will result in indexing errors


In [49]:
too_long_inputs = tokenizer(
    too_long,
    return_tensors = "pt",
    return_attention_mask = True,
    padding = "max_length",
    truncation = True
)

In [52]:
len(too_long_inputs["input_ids"].squeeze())

512

In [53]:
device = 0 if torch.cuda.is_available() else "cpu"
print(device)

0


In [ ]:
bert.model(device)
AutoModel.from_pretrained(checkpoint, device = device,) # device_map = "auto")

In [54]:
bert.eval()

BertModel(
  (embeddings): BertEmbeddings(
    (word_embeddings): Embedding(30522, 768, padding_idx=0)
    (position_embeddings): Embedding(512, 768)
    (token_type_embeddings): Embedding(2, 768)
    (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
    (dropout): Dropout(p=0.1, inplace=False)
  )
  (encoder): BertEncoder(
    (layer): ModuleList(
      (0-11): 12 x BertLayer(
        (attention): BertAttention(
          (self): BertSelfAttention(
            (query): Linear(in_features=768, out_features=768, bias=True)
            (key): Linear(in_features=768, out_features=768, bias=True)
            (value): Linear(in_features=768, out_features=768, bias=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (output): BertSelfOutput(
            (dense): Linear(in_features=768, out_features=768, bias=True)
            (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
            (dropout): Dropout(p=0.1, inplace=False)
  

In [56]:
with torch.no_grad():
    outputs = bert(**inputs, output_hidden_states = True)

In [58]:
outputs.last_hidden_state.shape

torch.Size([1, 17, 768])

In [59]:
outputs.last_hidden_state

tensor([[[-0.1813, -0.1627, -0.2402,  ..., -0.1174,  0.2389,  0.5933],
         [-0.1219,  0.2374, -0.8745,  ...,  0.3379,  0.4232, -0.2547],
         [ 0.3440,  0.2197, -0.0133,  ..., -0.1566,  0.2564,  0.2016],
         ...,
         [ 0.5548, -0.4396,  0.7075,  ...,  0.1718, -0.1337,  0.4442],
         [ 0.5042,  0.1461, -0.2642,  ...,  0.0728, -0.4193, -0.3139],
         [ 0.4306,  0.1996, -0.0055,  ...,  0.1924, -0.5685, -0.3189]]])

In [61]:
outputs.pooler_output.shape # [CLS]

torch.Size([1, 768])

In [62]:
outputs.hidden_states

(tensor([[[ 0.1686, -0.2858, -0.3261,  ..., -0.0276,  0.0383,  0.1640],
          [-0.2008,  0.1479,  0.1878,  ...,  0.9505,  0.9427,  0.1835],
          [-0.3319,  0.4860, -0.1578,  ...,  0.5669,  0.7301,  0.1399],
          ...,
          [-0.1509,  0.1222,  0.4894,  ...,  0.0128, -0.1437, -0.0780],
          [-0.3884,  0.6414,  0.0598,  ...,  0.6821,  0.3488,  0.7101],
          [-0.5870,  0.2658,  0.0439,  ..., -0.1067, -0.0729, -0.0851]]]),
 tensor([[[-0.0422,  0.0229, -0.2086,  ...,  0.1785, -0.0790, -0.0525],
          [-0.5901,  0.1755, -0.0278,  ...,  1.0815,  1.6212,  0.1523],
          [ 0.0323,  0.8927, -0.2348,  ...,  0.0032,  1.3259,  0.2274],
          ...,
          [ 0.6683,  0.2020, -0.0523,  ...,  0.0027, -0.2793,  0.1329],
          [-0.1310,  0.5102, -0.1028,  ...,  0.3445,  0.0718,  0.6305],
          [-0.3432,  0.2476, -0.0468,  ..., -0.1301,  0.1246,  0.0411]]]),
 tensor([[[-0.1382, -0.2264, -0.4627,  ...,  0.3514,  0.0516, -0.0463],
          [-0.8300,  0.4672,

In [63]:
# Which layer? Which token?
outputs.hidden_states[3].shape

torch.Size([1, 17, 768])

In [ ]:
# Mean pooling: take the mean of all token embeddings in a sequence
# Max pooling: takes the max for each feature for all token embeddings in a sequence
# Mean (max, sum) of the last four layers, then use [CLS]
# Concatenate for [CLS] all features from the last four layers: 4 * 768
# SentenceTransformers -> n_dimensional embedding for every input sequence (dynamic)

In [65]:
import torch
import torch.nn.functional as F
import numpy as np
import pandas as pd
from datasets import Dataset
from transformers import (
    AutoTokenizer,
    AutoModelForSequenceClassification,
    AutoModelForCausalLM
)
from transformers import (
    DataCollatorWithPadding,
    TrainingArguments,
    Trainer,
    EarlyStoppingCallback
)
from transformers import pipeline, GenerationConfig
import evaluate
from sklearn.metrics import classification_report, confusion_matrix
import matplotlib.pyplot as plt

In [66]:
blurbs = pd.read_parquet("bert_blurb_classifier/blurbs.parquet")

In [67]:
blurbs.head()

d1                                 author  \
0  Arts & Entertainment  Darren Wilsey, Daylle Deanna Schwartz   
1  Arts & Entertainment                           Otto Karolyi   
2  Arts & Entertainment                            Lisa Hunter   
3  Arts & Entertainment                             Glyn Macey   
4  Arts & Entertainment                         Barry Herniman   

                                     title          d0  published  \
0  The Musician's Guide to Licensing Music  Nonfiction 2010-02-16   
1   Traditional African and Oriental Music  Nonfiction 1999-09-01   
2               The Intrepid Art Collector  Nonfiction 2006-10-24   
3                       Acrylics Unleashed  Nonfiction 2013-04-01   
4             Painting Mood and Atmosphere  Nonfiction 2004-03-01   

            isbn                                               text  
0  9780823014873  Plug your music career into the lucrative new ...  
1  9780140231076  The aim of this book is to offer an introducti...  
2  9780307237132  Ready to upgrade your artwork from framed Mone...  
3  9781844487967  Glyn Maceys irrepressible energy and imaginati...  
4  9781844480012  The glowing transparency and sponteneity of wa...

In [68]:
enumerated = list(enumerate(blurbs["d1"].unique()))
id2label = {idx: genre for idx, genre in enumerated}
label2id = {genre: idx for idx, genre in enumerated}

In [69]:
id2label

{0: 'Arts & Entertainment',
 1: 'Biography & Memoir',
 2: 'Children’s Middle Grade Books',
 3: 'Cooking',
 4: 'Graphic Novels & Manga',
 5: 'Literary Fiction',
 6: 'Mystery & Suspense',
 7: 'Politics',
 8: 'Religion & Philosophy',
 9: 'Romance'}

In [70]:
blurbs["label"] = blurbs["d1"].replace(label2id)

In [71]:
blurbs.head()

d1                                 author  \
0  Arts & Entertainment  Darren Wilsey, Daylle Deanna Schwartz   
1  Arts & Entertainment                           Otto Karolyi   
2  Arts & Entertainment                            Lisa Hunter   
3  Arts & Entertainment                             Glyn Macey   
4  Arts & Entertainment                         Barry Herniman   

                                     title          d0  published  \
0  The Musician's Guide to Licensing Music  Nonfiction 2010-02-16   
1   Traditional African and Oriental Music  Nonfiction 1999-09-01   
2               The Intrepid Art Collector  Nonfiction 2006-10-24   
3                       Acrylics Unleashed  Nonfiction 2013-04-01   
4             Painting Mood and Atmosphere  Nonfiction 2004-03-01   

            isbn                                               text  label  
0  9780823014873  Plug your music career into the lucrative new ...      0  
1  9780140231076  The aim of this book is to offer an introducti...      0  
2  9780307237132  Ready to upgrade your artwork from framed Mone...      0  
3  9781844487967  Glyn Maceys irrepressible energy and imaginati...      0  
4  9781844480012  The glowing transparency and sponteneity of wa...      0

In [73]:
dataset = Dataset.from_pandas(blurbs[["text", "label"]])
blurbs["label"].nunique()

10

In [74]:
model_name = "bert-base-uncased"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForSequenceClassification.from_pretrained(
    model_name, num_labels = blurbs["label"].nunique()
)

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


In [75]:
model.config.id2label = id2label
model.config.label2id = label2id

In [86]:
def tokenize(examples):
    """Tokenize strings.

    Parameters
    ----------
    examples : dict
        Batch of texts

    Returns
    -------
    tokenized : dict
        Tokenized texts
    """
    tokenized = tokenizer(
        examples["text"],
    )

    return tokenized

In [87]:
split = dataset.train_test_split()
split

DatasetDict({
    train: Dataset({
        features: ['text', 'label'],
        num_rows: 10942
    })
    test: Dataset({
        features: ['text', 'label'],
        num_rows: 3648
    })
})

In [88]:
trainset = split["train"].map(tokenize, batched = True)
testset = split["test"].map(tokenize, batched = True)

Map: 100% 10942/10942 [00:04<00:00, 2241.18 examples/s]
Map: 100% 3648/3648 [00:01<00:00, 1958.12 examples/s]


In [89]:
trainset

Dataset({
    features: ['text', 'label', 'input_ids', 'token_type_ids', 'attention_mask'],
    num_rows: 10942
})

In [90]:
data_collator = DataCollatorWithPadding(tokenizer = tokenizer)

In [91]:
accuracy_metric = evaluate.load("accuracy")
f1_metric = evaluate.load("f1")

def compute_metrics(evaluations):
    """Compute metrics for a set of predictions.

    Parameters
    ----------
    evaluations : tuple
        Model logits/label for each text and texts' true labels

    Returns
    -------
    scores : dict
        The metric scores
    """
    # Split the model logits from the true labels
    logits, references = evaluations

    # Find the model prediction with the maximum value
    predictions = np.argmax(logits, axis = 1)

    # Calculate the scores
    accuracy = accuracy_metric.compute(
        predictions = predictions, references = references
    )
    f1 = f1_metric.compute(
        predictions = predictions,
        references = references,
        average = "weighted"
    )

    # Wrap up the scores and return them for display during logging
    scores = {"accuracy": accuracy["accuracy"], "f1": f1["f1"]}

    return scores

In [92]:
num_train_epochs = 15

In [93]:
per_device_train_batch_size = 32
per_device_eval_batch_size = 8

In [94]:
learning_rate = 3e-5

In [95]:
warmup_steps = (len(trainset) / per_device_train_batch_size) * num_train_epochs
warmup_steps = round(warmup_steps * 0.1)
print("Number of warm up steps:", warmup_steps)

Number of warm up steps: 513


In [96]:
weight_decay = 1e-2

In [97]:
training_args = TrainingArguments(
    output_dir = "data/bert_blurb_classifier",
    num_train_epochs = num_train_epochs,
    per_device_train_batch_size = per_device_train_batch_size,
    per_device_eval_batch_size = per_device_eval_batch_size,
    learning_rate = learning_rate,
    warmup_steps = warmup_steps,
    weight_decay = weight_decay,
    logging_steps = 100,
    evaluation_strategy = "epoch",
    save_strategy = "epoch",
    load_best_model_at_end = True,
    metric_for_best_model = "loss",
    save_total_limit = 3,
    push_to_hub = False
)

In [98]:
trainer = Trainer(
    model = model,
    tokenizer = tokenizer,
    data_collator = data_collator,
    args = training_args,
    train_dataset = trainset,
    eval_dataset = testset,
    compute_metrics = compute_metrics,
    callbacks = [EarlyStoppingCallback(early_stopping_patience = 3)]
)

In [ ]:
trainer.train()

In [99]:
fine_tuned = "bert_blurb_classifier/final"
tokenizer = AutoTokenizer.from_pretrained(fine_tuned)
model = AutoModelForSequenceClassification.from_pretrained(fine_tuned)

In [100]:
classifier = pipeline(
    "text-classification", model = model, tokenizer = tokenizer
)

In [111]:
sample = blurbs.sample(1)
#print(sample["text"].item())
classifier("1930s Europe was a tumultous time", top_k = None)

[{'label': 'Literary Fiction', 'score': 0.22967785596847534},
 {'label': 'Romance', 'score': 0.1994495838880539},
 {'label': 'Children’s Middle Grade Books', 'score': 0.16720600426197052},
 {'label': 'Biography & Memoir', 'score': 0.16302183270454407},
 {'label': 'Arts & Entertainment', 'score': 0.0830671563744545},
 {'label': 'Mystery & Suspense', 'score': 0.05628233775496483},
 {'label': 'Politics', 'score': 0.048288144171237946},
 {'label': 'Graphic Novels & Manga', 'score': 0.032358285039663315},
 {'label': 'Religion & Philosophy', 'score': 0.012297534383833408},
 {'label': 'Cooking', 'score': 0.008351278491318226}]

In [112]:
checkpoint = "gpt2"
gpt_tokenizer = AutoTokenizer.from_pretrained(checkpoint)
gpt = AutoModelForCausalLM.from_pretrained(checkpoint)

In [113]:
prompt = "It was the best of times, it was the"
tokenized = gpt_tokenizer(prompt, return_tensors = "pt", truncation = True)

In [114]:
with torch.no_grad():
    generated = gpt(**tokenized)

In [117]:
generated.logits.shape

torch.Size([1, 10, 50257])

In [118]:
last_token_logits = generated.logits[:, -1, :]

In [119]:
last_token_logits

tensor([[ -95.6606,  -94.0251,  -98.6486,  ...,  -98.9755, -100.9134,
          -94.9695]])

In [120]:
z = [2.0, 1.0, 1.0]
exponentiated = [np.exp(val) for val in z]
summed = np.sum(exponentiated)

exponentiated / summed

array([0.57611688, 0.21194156, 0.21194156])

In [121]:
probs = F.softmax(last_token_logits, dim = -1)

In [123]:
probs.shape

torch.Size([1, 50257])

In [126]:
probs[0, :10]

tensor([3.6413e-07, 1.8687e-06, 1.8348e-08, 6.0486e-09, 1.2955e-07, 3.2124e-08,
        9.7930e-07, 3.6522e-07, 2.3999e-06, 9.9195e-08])

In [127]:
next_token_id = torch.argmax(probs).item()
next_token = gpt_tokenizer.decode(next_token_id)

print("Next predicted token:", next_token)

Next predicted token:  worst


In [129]:
generated_token_ids = gpt.generate(**tokenized, max_new_tokens = 10)
generated = gpt_tokenizer.decode(generated_token_ids.squeeze())

print("Full sequence:", generated)

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


Full sequence: It was the best of times, it was the worst of times.

"I'm not


In [ ]:
seq = ["tokens"]
for i in range(4):
    current = seq.copy()
    output = gpt(current)
    seq = current

In [130]:
generator = pipeline("text-generation", model = gpt, tokenizer = gpt_tokenizer)

In [139]:
generated ,= generator(prompt, max_new_tokens = 4, do_sample = True, num_return_sequences = 5)
print(generated["generated_text"])

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


ValueError: too many values to unpack (expected 1)

In [140]:
generator(prompt, max_new_tokens = 4, do_sample = True, num_return_sequences = 5)

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


[{'generated_text': 'It was the best of times, it was the last of years,'},
 {'generated_text': 'It was the best of times, it was the best of times.'},
 {'generated_text': 'It was the best of times, it was the best of times,"'},
 {'generated_text': 'It was the best of times, it was the worst of times,"'},
 {'generated_text': 'It was the best of times, it was the best of times."'}]

In [141]:
generated = generator(
    prompt,
    do_sample = True,
    max_new_tokens = 4,
    top_k = 50,
    num_return_sequences = 5
)
for seq in generated:
    print(seq["generated_text"])

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


It was the best of times, it was the worst. We were
It was the best of times, it was the best of times,"
It was the best of times, it was the best of times.
It was the best of times, it was the worst. I'd
It was the best of times, it was the most wonderful of times


In [142]:
generated = generator(
    prompt,
    do_sample = True,
    max_new_tokens = 4,
    top_p = 0.9,
    num_return_sequences = 5
)
for seq in generated:
    print(seq["generated_text"])

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


It was the best of times, it was the worst of times,
It was the best of times, it was the best of times,"
It was the best of times, it was the worst.


It was the best of times, it was the worst of times.
It was the best of times, it was the worst of times,


In [144]:
generated = generator(
    prompt, 
    do_sample = True,
    max_new_tokens = 5,
    temperature = 50.0,
    num_return_sequences = 5
)
for seq in generated:
    print(seq["generated_text"])

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


It was the best of times, it was the saddlin,' Paul says
It was the best of times, it was the very toughest stuff imaginable --
It was the best of times, it was the finest!" he remarked triumph
It was the best of times, it was the right place
Ek
It was the best of times, it was the least to miss though (


In [147]:
gpt_tokenizer.pad_token_id = 50256
print("Pad token:", gpt_tokenizer.pad_token)

Pad token: <|endoftext|>


In [148]:
config = GenerationConfig(
    max_new_tokens = 25,
    do_sample = True, 
    temperature = 1.5,
    top_p = 0.8, 
    num_return_sequences = 5,
)
generator = pipeline(
    "text-generation",
    model = gpt,
    tokenizer = gpt_tokenizer,
    generation_config = config
)

In [149]:
generated = generator(prompt)
for seq in generated:
    print(seq["generated_text"])

It was the best of times, it was the best of times," the 32-year-old defender said, as he sat in a makeshift stand next to his post in
It was the best of times, it was the first real day of my year," the 21-year-old former United Nations World Cup soccer player said after the U.
It was the best of times, it was the worst."

Maurice Brown, a spokeswoman for Humber Valley Police, said that there were two complaints after the
It was the best of times, it was the worst of times. So what would you do?" He shrugged the memory away, as if taking his time with it.

It was the best of times, it was the greatest of times."

Rajesh had gone out of his way to highlight his father's legacy by being a true
